### PR TITLE
Added string comparison in when clauses

### PR DESCRIPTION
**Pull request by Ptival**
Note that this builds on top of #70.

### CODE REVIEW

**Comment by Ptival** [comment]
All tests pass at that point.

**Comment by Ptival** [comment]
@ztatlock Mergeit?

**Comment by ztatlock** [comment]
WOW PTIVAL.

THIS CODE.... SO GOOD.

I'm sitting here weeping at it's beauty.

My new religion centered on worship of this program.

Your commits represent the sacred of this new, emerging faith.

**Comment by Ptival** [comment]
@ztatlock ITS*

**Comment by ztatlock** [comment]
Hehe :) I can only claim lack of sleep to explain this one.

**Pull request merged**
