### PR TITLE
u-ssh monitor

### PR DESCRIPTION
**Pull request by d1jang**
The first version of u-ssh monitor has been implemented. This branch doesn't change any thing, but add one kernel file.

### CODE REVIEW

**Comment by d1jang** [comment]
This branch is totally unrelated to other parts of the compiler. It needs to be merged.

**Comment by ztatlock** [comment]
@d1jang cool!

Feel free to merge.

**Comment by Ptival** [comment]
@d1jang Ask again when you make changes after you've been greenlit :) (cf. 031dd30)

**Comment by ztatlock** [comment]
Sneaky... (though I think I may have done this before too on accident...)

**Pull request merged**
