### PR TITLE
u-ssh has started running in Kraken

### PR DESCRIPTION
**Pull request by d1jang**
u-ssh is fully incorporated with Kraken.
Take a look at ./test/u-ssh/kernel.krn.

The entire other components are built inside $KRAKEN/ssh-proto/kmsg-ssh

### CODE REVIEW

**Comment by d1jang** [comment]
Except for the first two changes, all the other changes are confined within ssh-proto directory.

**Comment by Ptival** [comment]
Hmm, do we want all that code in our codebase though? + @ztatlock

**Comment by ztatlock** [comment]
Well, ideally, we wouldn't have any outside code in the repo... 

If we had more time, I would advocate that we find a cleaner way to work with the ssh code.

However, since we are so close to the deadline, I am willing to take shortcuts.

OTOH, I'm not really sure how to review this PR...

**Comment by ztatlock** [comment]
Since we have absolute paths, we should be able to do this separately, but maybe it's better to just keep everything in one place for now?

I really don't know what's best.

Probably whatever is fastest.

**Comment by d1jang** [comment]
The cleanest way might be to make a diff patch which can be applicable to the ssh codbase so that we don;t have to add the entire ssh code to the repo. However, since nobody except for me has to look inside ssh now, how about adding the entire codebase so that we can make a change easily there for NOW, and make it cleaner later?

**Comment by ztatlock** [comment]
I think that this is an OK tradeoff for now.

I don't think making patches is worth our time at the moment.

@Ptival : thoughts?

**Comment by Ptival** [comment]
@ztatlock fine for me

**Comment by ztatlock** [comment]
@d1jang can you merge master into this branch?

**Comment by ztatlock** [comment]
Looks good to me! Merge at will!

**Pull request merged**
