### PR TITLE
Generating C Msg Lib

### PR DESCRIPTION
**Pull request by ztatlock**
Here's a first stab at generating the C msg lib for a given kraken spec.

What do you think @d1jang? I hope this can help with u-telnet and u-ssh!

Any thoughts @Ptival?

### CODE REVIEW

**Comment by ztatlock** [comment]
Going to add some more documentation and a get_param(i) function too.

**Comment by ztatlock** [comment]
@d1jang @Ptival I think this is ready to be merged so we can start on u-telnet and u-ssh. Can you look it over and let me know what you think?

**Comment by d1jang** [comment]
This looks okay to me. One subtlety is that endian conversion is need only for Coq monitors, not for any other implementation of monitors, for example, built in C or Python. This might be problematic when we test slaves with pre-existing C-monitors. But just being aware of this would be okay.

**Comment by ztatlock** [comment]
OK, int should always be sent in network order, which the internet standard RFC makes big endian.

So all components should use big endian for sending integers over sockets.

Ran valgrind on this and saw no leaks :)

**Pull request merged**
