### PR TITLE
Running WebKit via μ-quark

### PR DESCRIPTION
**Pull request by Ptival**
I pushed a first change. This runs a WebKit tab, and does the same as before (loop through our webpages).

Now, this needs some dependencies installed. I should probably now work on pulling these deps from the web, right?
And after that, a proper input?

What think @ztatlock @d1jang ?

Could you guys try running test/u-quark in this commit, and tell me if you see our webpages or a Python error?

### CODE REVIEW

**Comment by Ptival** [comment]
Sorry about the weird commit hours, I forgot to load the kernel module to resync my VM's date after it's been hibernating...

**Comment by d1jang** [comment]
This is a great first trial! I've successfully compiled u-quark, but when I tried to run it, I got the following error messages :
Traceback (most recent call last):
  File "/home/don/kraken/compiler/tmp/u-quark/client/screen.py", line 3, in <module>
    import msg, webkitlib as WK
  File "/home/don/kraken/compiler/tmp/u-quark/client/webkitlib.py", line 9, in <module>
    import webkit
  File "/usr/local/lib/python2.7/dist-packages/webkit/**init**.py", line 21, in <module>
    import webkit
ImportError: /usr/lib/libwebkitgtk-1.0.so.0: undefined symbol: soup_session_prefetch_dns

As you said, there's a library dependency issue here. I'm not sure it is possible to confine all libraries to the locally installed ones so that we can resolve this dependency problem like we did for Ynot.

**Comment by ztatlock** [comment]
I get these errors, which seem dependency related:

```
ztatlock@gear (u-quark-webkit) ~/kraken/compiler/u-quark
$ ./bin/kernel.sh 
Traceback (most recent call last):
  File "/Users/ztatlock/kraken/compiler/u-quark/client/screen.py", line 3, in <module>
    import msg, webkitlib as WK
  File "/Users/ztatlock/kraken/compiler/u-quark/client/webkitlib.py", line 3, in <module>
    import gobject
ImportError: No module named gobject
Fatal error: exception Failure("recv - wrong # of bytes")

...
```

Looking into it more now.

**Comment by ztatlock** [comment]
Ltac to decide if two lists are permutations:

```
Lemma rotPermCons :
  forall (T : Type) (e : T) (l1 l2 : list T),
  Permutation (l1 ++ e :: nil) l2 ->
  Permutation (e :: l1) l2.
Proof.
  intros. apply perm_trans with (l' := l1 ++ e :: nil); auto.
  rewrite <- (app_nil_r (e :: l1)). apply Permutation_middle.
Qed.

Lemma rotPermApp :
  forall (T : Type) (l1a l1b l2 : list T),
  Permutation (l1b ++ l1a) l2 ->
  Permutation (l1a ++ l1b) l2.
Proof.
  intros. apply perm_trans with (l' := l1b ++ l1a); auto.
  apply Permutation_app_comm.
Qed.

Ltac stepPerm :=
  (rewrite app_ass; simpl)
  || constructor
  || apply Permutation_app_head
  || (apply rotPermCons; simpl)
  || (apply rotPermApp; simpl).

Ltac decidePerm :=
  repeat stepPerm.
```

**Comment by Ptival** [comment]
The three previous commits make things nicer. It's unfortunate that they are in that branch though, as I would advise you to build on top of them...

Maybe we could consider merging this branch (who wants to code review it?), and creating a new branch for "real micro-quark".

Comments are welcome.

**Comment by ztatlock** [comment]
If all tests pass, then this is good to merge into master.

**Pull request merged**
