### PR TITLE
fix state-00 test: update for msg lib, tweak Makefile

### PR DESCRIPTION
**Pull request by ztatlock**
@Ptival another bug fix...

### CODE REVIEW

**Comment by Ptival** [comment]
For the record, what do the changes in the Makefile achieve?

**Comment by ztatlock** [comment]
The client Makefile conditionally includes another makefile, Makefile.client, if it exists.

This functionality is useful when your components are written in C and need to be compiled.

However, that test was being done at the top of the client Makefile, which make "client" the main rule instead of "all".

By lowering that test, "all" is correctly restored to its role as the main rule in the client Makefile.

**Comment by Ptival** [comment]
Seems fine then. Merge time!

**Comment by ztatlock** [comment]
This closes issue #9.

**Pull request merged**
